name: shindenshin
description: Layer communication package. It helps to develop data layer with models and API connectors, which will be used by BLoC to build UI.
version: 0.5.0
homepage: https://github.com/justjew/shindenshin

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  dio: ^5.1.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  test: ^1.17.12

flutter:
