name: shindenshin
description: Layer communication package. It helps to develop data layer with models and API connectors, which will be used by BLoC to build UI.
version: 0.1.0
homepage: https://github.com/justjew/shindenshin

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  dio: ^4.0.4
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  test: ^1.17.12

flutter:
